pipeline:
  build-and-push:
    image: plugins/docker
    settings:
      repo: lblod/ldes-make-object-service
      tags: "feature-${CI_COMMIT_BRANCH##feature/}"
    secrets: [docker_username, docker_password]
when:
  event: push
  branch: feature/*
