steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: lblod/ldes-make-object-service
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: push
    branch: [master, main]
