pipeline:
  build:
    image: plugins/docker
    settings:
      repo: lblod/job-compression-service
      tags: "${CI_COMMIT_TAG##v}"
    secrets: [ docker_username, docker_password ]
when:
  event: tag
  tag: v*
