pipeline:
  build:
    image: plugins/docker
    settings:
      repo: lblod/ldes-make-object-service
      tags: latest
    secrets: [docker_username, docker_password]
when:
  branch: master
  event: push
